-- Phase 08-04: Study Plan first-session target progress threshold.
--
-- A new StudyPlan column that controls when a "new" card
-- (state="new", progress < threshold) graduates to the review
-- bucket (state="review", counts toward reviewsPerDay instead of
-- newPerDay). The threshold is the minimum Card.progress value
-- (0-1 float) the buildQueue re-bucket uses.
--
-- Default 0.80 = a card needs 80% of (stability / (stability +
-- difficulty)) to graduate. For a brand-new card with
-- stability=10 days and difficulty=5, progress = 10/15 = 0.667
-- (still new). After a few successful reviews that grow
-- stability to 40+ days at the same difficulty, progress hits
-- 0.80+ and the card moves to review. The FSRS 6 scheduler then
-- takes over with the natural interval.
--
-- Bound rationale (validated in the Zod studyPlanSchema):
--   < 0.5 — too easy (almost every card graduates immediately,
--           review cap hits instantly, "new" cap never useful)
--   > 1.0 — mathematically impossible (progress is bounded
--           above by stability/(stability+difficulty) which is
--           < 1 for any positive difficulty)
--
-- NOT NULL with a DB default so existing StudyPlan rows from
-- Phase 2/6/7/8-01 are backfilled automatically; migration is
-- purely additive.

ALTER TABLE "StudyPlan" ADD COLUMN "firstSessionTargetProgress" REAL NOT NULL DEFAULT 0.80;
